version: '3'

services:
  reverse-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  webserver:
    image: nginx
    ports: 
      - 8001:80
    volumes:
      - ./web/wwwroot:/user/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf

  webserver2:
    image: nginx
    ports: 
      - 8002:80
    volumes:
      - ./web/wwwroot:/user/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf

volumes:
  wwwroot:
