version: '3'

services:
  reverse-proxy:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  auth:
    image: nginx
    depends_on:
        - reverse-proxy
    volumes:
      - ./auth/wwwroot:/usr/share/nginx/html/auth
      - ./auth/nginx.conf:/etc/nginx/nginx.conf

  webserver:
    image: nginx
    depends_on:
        - reverse-proxy
    volumes:
      - ./web/wwwroot:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf

  webserver2:
    image: nginx
    depends_on:
      - reverse-proxy
    volumes:
      - ./web/wwwroot:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
